/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CountryImport } from './routes/$country'
import { Route as IndexImport } from './routes/index'
import { Route as CountryVolcanoImport } from './routes/$country_.$volcano'

// Create/Update Routes

const CountryRoute = CountryImport.update({
  path: '/$country',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CountryVolcanoRoute = CountryVolcanoImport.update({
  path: '/$country/$volcano',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$country': {
      preLoaderRoute: typeof CountryImport
      parentRoute: typeof rootRoute
    }
    '/$country/$volcano': {
      preLoaderRoute: typeof CountryVolcanoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CountryRoute,
  CountryVolcanoRoute,
])

/* prettier-ignore-end */
